apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-stateful-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: apps
    repoURL: >-
      https://gitlab.com/masaki-oomura/simple-stateful-app.git
    #ここを自分のリポジトリのURLに変更します
    #例：https://gitlab.com/<your-username>/simple-stateful-app.git
    targetRevision: main
  project: simple-stateful-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true