apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: simple-stateful-app
    server: 'https://kubernetes.default.svc'
  source:
    path: manifest/namespace
    repoURL: >-
      https://gitlab.com/masaki-oomura/simple-stateful-app.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true