apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: manifest/namespace
    repoURL: >-
      https://gitlab.com/masaki-oomura/simple-stateful-app.git
    #ここを自分のリポジトリのURLに変更します
    #例：https://gitlab.com/<your-username>/simple-stateful-app.git
    targetRevision: main
  project: simple-stateful-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true