apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: simple-stateful-app
    server: 'https://kubernetes.default.svc'
  source:
    path: manifest/nodejs
    repoURL: >-
      https://gitlab.com/quay.io/rh_ee_kmotojim/simple-stateful-app.git
    #自身のGitlabリポジトリ名に変更します
    targetRevision: main
  project: simple-stateful-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true